### ISSUE TITLE
Integrate Build Process with Launch4j

### ISSUE THREAD

**Issue by cryptokat** [semuxproject/semux#228]
I believe Semux will be more user-friendly by providing an executable file than a bat file.

### Todos

- [x] build a fat jar from maven
- [x] add launch4j integration
- [x] automate wrapper testing using appveyor

### Links 

- http://launch4j.sourceforge.net/
- https://github.com/lukaszlenart/launch4j-maven-plugin

**Comment by semuxproject** [comment]
Does launch4j also include an installer generator, or we only need an executable? 

Related issue #64

**Comment by cryptokat** [comment]
I am on this. There are basically 2 approaches:

1. Provide an installer for each platform (e.g. parity)
![selection_408](https://user-images.githubusercontent.com/32390172/32958786-7c0ac374-cbfa-11e7-9dcf-371df51bdff3.png)
2. Provide a single executable file (e.g. go-ethereum)

I will look into these 2 approaches to see which of them is more appropriate under the tooling of launch4j.

**Comment by cryptokat** [comment]
### Links

- Cross platform installer izpack: http://izpack.org/
- Launch4j: http://launch4j.sourceforge.net/
- Package hosting: https://packagecloud.io/

**Comment by cryptokat** [comment]
independent executable file on windows platform:
![screenshot from 2017-11-19 15-19-46](https://user-images.githubusercontent.com/32390172/32988342-5a134e14-cd3d-11e7-80b1-aa28df8f404d.png)

**Comment by cryptokat** [comment]
Launch4j integration is addressed in https://github.com/semuxproject/semux/pull/256
https://github.com/semuxproject/semux/issues/64 will be addressed in another pull request once #256 has been reviewed & merged
